### ISSUE TITLE
How do I contact you?

### ISSUE THREAD

**Issue by tg12** [tattooday/quant-trading#1]
How do I contact you about collaboration work? I have got some idea's and putting together a project. If you want to join us.

You work is amazing! We could rule the world if we get our heads together. 

If you want to join us...

https://discord.gg/6je56P

**Comment by tattooday** [comment]
Hi, tg12, 
Thx for the invitation, I'm glad you like it. 
You can send me an email. My email is tattooday@yandex.com.
